Converted icons to SVG
oliverklee/ext-seminars pull request #1743
Opened 2022-11-03 20:22 UTC by Braunson

As per #1522, 

- Converted gif/png icons to SVG format
- Updated CHANGELOG.md

2022-11-04 14:28 UTC, oliverklee requested changes
Thank you for this contribution! :heart: :cookie:

You'll also need to update all references to these files. You can search for `.png` and `.gif` in these files/folders:
- `Configuration/TCA/`
- `Classes/BackEnd/EventsList.php`
- `Resources/Public/CSS/BackEnd/BackEnd.css`
- `ext_localconf.php`
- `ext_tables.php`

2022-11-04 14:28 UTC, oliverklee commented on CHANGELOG.md
> +- Converted icons from gif/png to SVG (#1522)
This should be the ID of the PR, not of the ticket. (This allows people to click on the ID in the changelog and directly see the changes.)

Also, please move this to the `Added` section.

2022-11-08 16:17 UTC, Braunson commented
@oliverklee Ah yes, the references have been updated, so has the CHANGELOG.

2022-11-08 17:06 UTC, oliverklee commented
The SVG icons look *very* strange in my backend (see screenshot) - they seem to have only one (foreground) color and seem to be very smooth so that most of the details are lost.
![grafik](https://user-images.githubusercontent.com/765746/200629531-207b1803-c542-457b-9081-0336eae38044.png)

How did you create/convert the icons?

2022-11-08 17:06 UTC, oliverklee requested changes
I think something has gone wrong during the conversion to SVG.

2022-11-08 17:09 UTC, oliverklee commented
If you like, we can also do this in smaller PRs (for which you'll need to use git branches for the PRs) so we can get this merged more quickly:
- BE module icon
- content wizard icon
- button icons in the BE module (canceled, confirmed, edit, hide, new, print, unhide)

2023-04-07 00:51 UTC, closed without merging