Replace renderAsRichText() by pi_RTEcssText() method
oliverklee/ext-seminars pull request #2374
Opened 2023-01-04 09:20 UTC by djangones

A fix for link handler links (t3://) not parsed anymore in Typo3 11, as discussed in #2372.

2023-01-04 09:42 UTC, oliverklee requested changes
We also need to adapt the call in line 2302 in `getOrganizersMarkerContent` and then can remove the `renderAsRichText` method.

2023-01-04 09:55 UTC, djangones commented
Was not sure about removing that method completely but her you go...

2023-01-04 10:21 UTC, oliverklee requested changes

2023-01-04 10:21 UTC, oliverklee commented on Classes/FrontEnd/DefaultController.php
> -        return HtmlViewHelper::renderStatic($arguments, $childrenClosure, new NullRenderingContext());
We probably then also can remove the `use` of `HtmlViewHelper` and `NullRenderingContext` now.

2023-01-09 11:59 UTC, oliverklee approved these changes

2023-01-09 11:59 UTC, oliverklee approved these changes
Looks good (and works fine). Thanks for contributing, @djangones! :heart:

2023-01-09 12:01 UTC, merged