[CLEANUP] Switch emailing in the EmailService from oelib mail functions to the Core SwiftMailer
oliverklee/ext-seminars pull request #676
Opened 2021-01-07 21:43 UTC by Konafets

Closes #613

2021-01-11 22:43 UTC, Konafets commented
This PR is ready for review.

2021-01-16 10:31 UTC, oliverklee requested changes

2021-01-16 10:31 UTC, oliverklee commented on Tests/LegacyUnit/Service/EmailServiceTest.php
> +    private function createMailMessageMock(): MailMessage
Please see my review of #675 about mocking the `send` method.

2021-01-16 10:31 UTC, oliverklee commented on Tests/LegacyUnit/Service/EmailServiceTest.php
> +    public function purgeMockedInstancesRemovesInstanceFromTypo3InstanceBuffer()
Please see my review of #675 about moving this to a trait.

2021-01-16 10:31 UTC, oliverklee commented on Tests/LegacyUnit/Service/EmailServiceTest.php
> +        self::assertEmpty($this->mockedClassNames);
Please be as specific as possible in the tests: `self::assertSame([], …)`

2021-01-16 10:31 UTC, oliverklee commented on Classes/Service/EmailService.php
> +            $firstOrganizer = $event->getFirstOrganizer();
Let's rename this so the role is more clear: `$firstOrganizer` -> `$replyTo`

2021-01-16 21:42 UTC, oliverklee commented
I have created the two traits for you to use: #683

2021-01-17 23:10 UTC, oliverklee requested changes
The same changes as in the other PR apply.

2021-01-18 22:35 UTC, oliverklee approved these changes

2021-01-18 22:36 UTC, merged