[CLEANUP] Stop using Translator and TranslatorRegistry
oliverklee/ext-seminars pull request #715
Opened 2021-01-26 18:20 UTC by Konafets

Closes #702

2021-01-26 18:32 UTC, oliverklee requested changes

2021-01-26 18:32 UTC, oliverklee commented on Classes/ViewHelper/Countdown.php
> +            LocalizationUtility::translate(
Let let's put this `translate` call into a single line to make this method less long (vertically).

2021-01-26 18:32 UTC, oliverklee commented on Classes/Email/Salutation.php
> +            LocalizationUtility::translate(
Let let's put this `translate` call into a single line to make this method less long (vertically).

2021-01-28 18:04 UTC, Konafets commented
Wondering, why suddenly an unrelated test fails. Will investigate this tomorrow.

2021-01-28 19:12 UTC, oliverklee commented
The failure probably is an incomplete mock: https://github.com/oliverklee/ext-seminars/issues/718

2021-01-28 19:21 UTC, oliverklee approved these changes

2021-01-28 19:21 UTC, merged